# -*- coding: utf-8 -*-
"""MS2026023_MLAssignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Vibushita/4ae31909321f448fb8b9ca208c0dce9b/untitled2.ipynb
"""

import pandas as pd
import numpy as np
import itertools

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

df = pd.read_csv("MS2026023_train_var1.csv")

print(df.head())
print(df.columns)

all_features = ['x1','x2','x3','x4','x5','x6']

y = df['y']

best_r2 = -999
best_mse = float('inf')

best_degree = None
best_features = None

for n_features in range(1, len(all_features)+1):

    for subset in itertools.combinations(
        all_features,
        n_features
    ):

        X = df[list(subset)]

        for degree in range(1,11):

            model = Pipeline([
                ('poly',
                 PolynomialFeatures(degree=degree)),
                ('linear',
                 LinearRegression())
            ])

            r2_scores = cross_val_score(
                model,
                X,
                y,
                cv=5,
                scoring='r2'
            )

            mse_scores = cross_val_score(
                model,
                X,
                y,
                cv=5,
                scoring='neg_mean_squared_error'
            )

            mean_r2 = r2_scores.mean()
            mean_mse = -mse_scores.mean()

            if (
                mean_r2 > best_r2
                or
                (
                    abs(mean_r2 - best_r2) < 1e-6
                    and mean_mse < best_mse
                )
            ):

                best_r2 = mean_r2
                best_mse = mean_mse

                best_degree = degree
                best_features = subset

print("\nBEST MODEL")

print("Degree =", best_degree)
print("Features =", best_features)
print("CV R2 =", best_r2)
print("CV MSE =", best_mse)

import matplotlib.pyplot as plt

X = df[list(best_features)]

r2_results = []
mse_results = []

for degree in range(1,11):

    model = Pipeline([
        ('poly', PolynomialFeatures(degree=degree)),
        ('linear', LinearRegression())
    ])

    r2 = cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring='r2'
    ).mean()

    mse = -cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring='neg_mean_squared_error'
    ).mean()

    r2_results.append(r2)
    mse_results.append(mse)

fig, ax1 = plt.subplots(figsize=(8,5))

ax1.plot(
    range(1,11),
    r2_results,
    marker='o',
    color='blue'
)

ax1.set_xlabel("Degree")
ax1.set_ylabel("CV R²", color='blue')

ax2 = ax1.twinx()

ax2.plot(
    range(1,11),
    mse_results,
    marker='s',
    color='red'
)

ax2.set_ylabel("CV MSE", color='red')

plt.title("VAR1: Degree vs CV R² and MSE")

plt.show()

# VAR1 Degree Table

table_var1 = pd.DataFrame({
    'Degree': range(1,11),
    'CV_R2': np.round(r2_results, 4),
    'CV_MSE': np.round(mse_results, 4)
})

print("\nVAR1 Degree Selection Table")
print(table_var1)

table_var1.to_csv(
    "var1_degree_table.csv",
    index=False
)

import itertools

feature_scores = []

features = [
    'x1','x2','x3',
    'x4','x5','x6'
]

for subset_size in range(1,7):

    best_subset_score = -999

    for subset in itertools.combinations(
        features,
        subset_size
    ):

        X = df[list(subset)]

        model = Pipeline([
            ('poly',
             PolynomialFeatures(degree=4)),
            ('linear',
             LinearRegression())
        ])

        score = cross_val_score(
            model,
            X,
            y,
            cv=5,
            scoring='r2'
        ).mean()

        best_subset_score = max(
            best_subset_score,
            score
        )

    feature_scores.append(
        best_subset_score
    )

plt.figure(figsize=(8,5))

plt.plot(
    range(1,7),
    feature_scores,
    marker='o'
)

plt.xlabel("Number of Features")
plt.ylabel("Best CV R²")
plt.title("VAR1: Feature Count vs CV R²")

plt.grid(True)

plt.show()

X = df[list(best_features)]

final_model_var1 = Pipeline([
    ('poly',
     PolynomialFeatures(
         degree=best_degree
     )),
    ('linear',
     LinearRegression())
])

final_model_var1.fit(X, y)

test = pd.read_csv(
    "MS2026023_test_var1.csv"
)

X_test = test[list(best_features)]

pred = final_model_var1.predict(X_test)

submission = pd.DataFrame({
    'y': pred
})

submission.to_csv(
    "MS2026023_pred_var1.csv",
    index=False
)

df = pd.read_csv(
    "MS2026023_train_var2.csv"
)

all_features = ['x1','x2','x3']
y = df['y']

best_r2 = -999
best_mse = float('inf')

best_degree = None
best_features = None

for n_features in range(1,4):

    for subset in itertools.combinations(
        all_features,
        n_features
    ):

        X = df[list(subset)]

        for degree in range(1,21):

            model = Pipeline([
                ('poly',
                 PolynomialFeatures(
                     degree=degree
                 )),
                ('linear',
                 LinearRegression())
            ])

            r2_scores = cross_val_score(
                model,
                X,
                y,
                cv=5,
                scoring='r2'
            )

            mse_scores = cross_val_score(
                model,
                X,
                y,
                cv=5,
                scoring='neg_mean_squared_error'
            )

            mean_r2 = r2_scores.mean()
            mean_mse = -mse_scores.mean()

            if (
                mean_r2 > best_r2
                or
                (
                    abs(mean_r2 - best_r2) < 1e-6
                    and mean_mse < best_mse
                )
            ):

                best_r2 = mean_r2
                best_mse = mean_mse

                best_degree = degree
                best_features = subset

print("\nBEST MODEL")

print("Degree =", best_degree)
print("Features =", best_features)
print("CV R2 =", best_r2)
print("CV MSE =", best_mse)

best_degree_scores = []
best_degree_mse = []

for degree in range(1,21):

    best_r2_deg = -999
    best_mse_deg = None

    for subset_size in range(1,4):

        for subset in itertools.combinations(
            all_features,
            subset_size
        ):

            X = df[list(subset)]

            model = Pipeline([
                ('poly',
                 PolynomialFeatures(
                     degree=degree
                 )),
                ('linear',
                 LinearRegression())
            ])

            r2 = cross_val_score(
                model,
                X,
                y,
                cv=5,
                scoring='r2'
            ).mean()

            mse = -cross_val_score(
                model,
                X,
                y,
                cv=5,
                scoring='neg_mean_squared_error'
            ).mean()

            if r2 > best_r2_deg:

                best_r2_deg = r2
                best_mse_deg = mse

    best_degree_scores.append(
        best_r2_deg
    )

    best_degree_mse.append(
        best_mse_deg
    )

fig, ax1 = plt.subplots(figsize=(10,6))

ax1.plot(
    range(1,21),
    best_degree_scores,
    marker='o',
    color='blue'
)

ax1.set_xlabel("Degree")
ax1.set_ylabel("CV R²", color='blue')

ax2 = ax1.twinx()

ax2.plot(
    range(1,21),
    best_degree_mse,
    marker='s',
    color='red'
)

ax2.set_ylabel("CV MSE", color='red')

plt.title("VAR2: Degree vs CV R² and MSE")

plt.show()

# VAR2 Degree Table

table_var2 = pd.DataFrame({
    'Degree': range(1,21),
    'CV_R2': np.round(best_degree_scores, 4),
    'CV_MSE': np.round(best_degree_mse, 4)
})

print("\nVAR2 Degree Selection Table")
print(table_var2)

table_var2.to_csv(
    "var2_degree_table.csv",
    index=False
)

feature_scores = []
feature_labels = []

for subset_size in range(1,4):

    best_subset_score = -999
    best_subset = None

    for subset in itertools.combinations(
        all_features,
        subset_size
    ):

        X = df[list(subset)]

        model = Pipeline([
            ('poly',
             PolynomialFeatures(
                 degree=best_degree
             )),
            ('linear',
             LinearRegression())
        ])

        score = cross_val_score(
            model,
            X,
            y,
            cv=5,
            scoring='r2'
        ).mean()

        if score > best_subset_score:

            best_subset_score = score
            best_subset = subset

    feature_scores.append(
        best_subset_score
    )

    feature_labels.append(
        str(best_subset)
    )

plt.figure(figsize=(8,5))

plt.bar(
    feature_labels,
    feature_scores
)

plt.ylabel("Mean CV R²")
plt.xlabel("Feature Subset")

plt.title(
    "VAR2: Best Feature Subset"
)

plt.show()

X = df[list(best_features)]

final_model_var2 = Pipeline([
    ('poly',
     PolynomialFeatures(
         degree=best_degree
     )),
    ('linear',
     LinearRegression())
])

final_model_var2.fit(X, y)

test = pd.read_csv(
    "MS2026023_test_var2.csv"
)

X_test = test[list(best_features)]

pred = final_model_var2.predict(X_test)

pd.DataFrame({
    'y': pred
}).to_csv(
    "MS2026023_pred_var2.csv",
    index=False
)

